### ISSUE TITLE
No sub formatter found in 0.4.5+

### ISSUE THREAD

**Issue by nathany-copia** [ash-project/igniter#154]
**Describe the bug**

Upgrading from Igniter 0.4.4 to 0.4.5 or 0.4.7 results in this error for the `use Igniter.Mix.Task` line in my mix task.

```
** (Rewrite.DotFormatterError) No sub formatter found in "priv/*/data_migrations"
    (rewrite 1.1.0) lib/rewrite/dot_formatter.ex:133: Rewrite.DotFormatter.read!/2
    (igniter 0.4.5) lib/igniter.ex:109: Igniter.new/0
    (copia 0.0.1) lib/mix/tasks/datafeed.gen.ex:11: Mix.Tasks.Datafeed.Gen.run/1
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /opt/homebrew/bin/mix:2: (file)
```

**To Reproduce**

I'm not sure what you would need. Does the existence of exs files in the `priv/repo/data_migrations` folder trigger this?

**Expected behavior**

Continue to work as in 0.4.4.

\*\* Runtime

```
❯ elixir -v
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.17.3 (compiled with Erlang/OTP 26)
```

- Elixir version
- Erlang version
- OS - macOS 15.1
- Igniter version 0.4.5+
- any related extension versions

**Additional context**

**Comment by zachallaun** [comment]
@NickNeck Any ideas on this?

**Comment by NickNeck** [comment]
@nathany-copia it looks like that your `.formatter.exs` has the line `subdirectories: ["priv/*/migrations"],` but the file `priv/repo/migrations/.formatter.exs` is missing (the dir `repo` could have any other name).

Could you check this with:
```shell
find . -name .formatter.exs -not -path "./deps*"
```
For one of my projects I get:
```
./priv/repo/migrations/.formatter.exs
./.formatter.exs
```

**Comment by NickNeck** [comment]
One more thing. `Rewrite` keeps the `DotFormatter` up to date during an `igniter` run. The exception could be thrown if `igniter` updates the `.formatter.exs` before the source for the sub formatter has been created.

**Comment by zachallaun** [comment]
@NickNeck So to solve this, we should bump rewrite to 1.1.1 and use the new ignore_sub_formatters option everywhere we read a dotformatter?

**Comment by zachdaniel** [comment]
(Not back yet) I think we want to ensure we write subformatters before the parent formatter, or we want to make sure that subformatters are only ignored when not present. Is that what the ignore subformatters option does?

**Comment by NickNeck** [comment]
@zachdaniel with the `ignore_missing_sub_formatters` option, a missing sub-formatter will be ignored instead of returning or throwing an error. If all sub-formatter files are available, they will be read.

**Comment by epinault** [comment]
+1 one on this issue. Is the solution to create the .formatter file? I don t recall it needed in the migrations but maybe something that was added later on in Phx?

**Comment by zachdaniel** [comment]
Sounds like the new option is the way 👍

**Comment by NickNeck** [comment]
@zachdaniel I think the new `ignore_missing_sub_formatters` option is a good way, because `mix format` also does not check if the sub formatters are available.

**Comment by nathany-copia** [comment]
Thanks for this.

@zachdaniel Sorry I missed the notification for your earlier message. I saw the same thing you did:

```
./priv/repo/migrations/.formatter.exs
./.formatter.exs
```

**Comment by NickNeck** [comment]
> Thanks for this.
> 
> @zachdaniel Sorry I missed the notification for your earlier message. I see the same thing you did:
> 
> ```
> ./priv/repo/migrations/.formatter.exs
> ./.formatter.exs
> ```

But the error message says `No sub formatter found in "priv/*/data_migrations"` and there is no `.formatter.exs` in the directory `priv/*/data_migrations`. There is only one sub formatter in `priv/*/migrations`.

**Comment by zachdaniel** [comment]
I'm not really sure what the original root cause for the issue is, but it shouldn't matter any more right? igniter will do the right thing regardless w/ the new option from rewrite.

**Comment by NickNeck** [comment]
@zachdaniel the root cause for the issue is a misconfigured formatter. If in a formatter has sub-formatters configured with the `:subdirectories` option, then a `.formater.exs' file is searched in those directories. The task `mix format` does not throws an error or warning if one of this sub-formatter is missing. In this case `mix format` does not format files in the affected directories. If we would use `Mix.Task.Format.formmater_for_file` in this project with a file name that lays in an affected directory we would get the 'nearest' formatter. The `formatter_for_file` function also does not check if the file name is covered by the `:input` option of the formatters.

`Rewrite.DotFormatter` works in the same way if the option `ignore_missing_sub_formatters` is used. Just to say, the `Rewrite.DotFormatter` does not use any functions from `Mix.Task.Format`.

So with the `ignore_missing_sub_formatters` option, `igniter` handles formatting like `mix format`. The worst thing that can happen is that files are not formatted or not formatted in a way that a user expects, but this is true for both `igniter` and `mix format`.
