### ISSUE TITLE
find_all_matching_modules returns igniter to all files

### ISSUE THREAD

**Issue by georgevanderson** [ash-project/igniter#179]
**Describe the bug**
I am not totally sure if this is a bug, since this function does not have documentation about whether to discard the igniter of the function.  I was expecting that similar to the rest of the `find` functions, passing in a new Igniter would return an igniter containing only modules which match the predicate, not all elixir files https://github.com/ash-project/igniter/blob/main/lib/igniter/project/module.ex#L233-L235

**To Reproduce**
N/A

**Comment by zachdaniel** [comment]
This isn't a bug :) All that that line of code does is ensure that all elixir files files are loaded into the igniter to be searched.  It is okay for files to be loaded in the igniter but never be changed. We have to load them all in so that we can search them.

So `find_all_matching_modules` is not about what is modified in the igniter itself, but what modules it returns. It by design loads all elixir files, and then returns the igniter plus a list of matching modules.

**Comment by zachdaniel** [comment]
Are you relying on which files are loaded into the igniter struct for something? If so, you should probably not be.
